# Generated by Django 4.0.1 on 2022-03-06 20:08

from django.db import migrations, models
import utils.rename


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otherWebsite',
        ),
        migrations.RemoveField(
            model_name='user',
            name='workEmail',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=utils.rename.Rename.rename, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to=utils.rename.Rename.rename, verbose_name='Задний фон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$320000$O5g2WssnxObrFTfjCGJeiT$bhpSGnd10btPljYyKDXqFhhOcOWr7qjEzeAV26tYL8w=', max_length=128, verbose_name='Пароль'),
        ),
    ]
