# Generated by Django 4.0.1 on 2022-03-06 21:06

from django.db import migrations, models
import utils.rename


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_otherwebsite_remove_user_workemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='welcome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Строка приветствия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=utils.rename.Rename.rename, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to=utils.rename.Rename.rename, verbose_name='Задний фон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$320000$A3TlhXzqIsoNjvW3hFXAKJ$G/Vf6wuKLqltA/N2gCC1IsOG4ZxMuAgONlqSV4JLFK0=', max_length=128, verbose_name='Пароль'),
        ),
    ]
