# Generated by Django 4.0.1 on 2022-03-06 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.rename


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_welcome_alter_user_avatar_alter_user_bg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=utils.rename.Rename.rename, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to=utils.rename.Rename.rename, verbose_name='Задний фон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$320000$M1Za0QbdEK3GpJUidZUgTJ$5ayyQIM0KKnZl4mCYLGvM1NrsrDEUHzv11zzbzskgwM=', max_length=128, verbose_name='Пароль'),
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок')),
                ('image', models.ImageField(upload_to=utils.rename.Rename.rename, verbose_name='Изображение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_images', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
