# Generated by Django 4.0.3 on 2022-04-09 12:15

from django.db import migrations, models
import utils.rename


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_avatar_alter_user_bg_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wechat',
            field=models.URLField(blank=True, null=True, verbose_name='Wechat'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=utils.rename.Rename.rename, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to=utils.rename.Rename.rename, verbose_name='Задний фон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$320000$DeuGj2rTPKriMKjvB8cNdE$Ej4EtYsSu9ZAgYDHFdzH9brNLZ0Gwe8NDQtzlnnCD2Q=', max_length=128, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(upload_to=utils.rename.Rename.rename, verbose_name='Изображение'),
        ),
    ]
