# Generated by Django 4.0.3 on 2022-04-10 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_avatarhidden_alter_user_avatar_alter_user_bg_and_more'),
        ('users', '0010_alter_user_avatar_alter_user_bg_alter_user_password_and_more'),
    ]

    operations = [
    ]
