version: "3.8"

services:
    web:
        build: .
        container_name: django
        command: sh -c "gunicorn -b 0.0.0.0:8000 core.wsgi --reload"
        volumes:
            - .:/app
            - media:/app/media/
            - static:/app/static/
        ports:
            - "8000:8000"
        environment:
            - POSTGRES_DB=temir
            - POSTGRES_USER=temirUser
            - POSTGRES_PASSWORD=temir123
            - POSTGRES_HOST=pgdb
        depends_on:
            - pgdb
    pgdb:
        image: postgres:latest
        container_name: pgdb
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
        - POSTGRES_DB=temir
        - POSTGRES_USER=temirUser
        - POSTGRES_PASSWORD=temir123
    nginx:
        image: linuxserver/swag
        restart: always
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Bishkek
            - URL=temir.ae
            - SUBDOMAINS=api
            - VALIDATION=http
            - ONLY_SUBDOMAINS=true
            - STAGING=false
        depends_on:
            - web
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/nginx.conf:/config/nginx/site-confs/default
            - media:/usr/media/
            - lets:/config/keys/
            - static:/usr/static/
volumes:
  postgres_data:
  static:
  media:
  lets:
